export const UPDATE_NAMES = 'UPDATE_NAMES';
export const DELETE_PERSON = 'DELETE_PERSON';
export const TOGGLE_PERSON = 'TOGGLE_PERSON';
export const HANDLE_INPUT = 'HANDLE_INPUT';
export const TOGGLE_OVERLAY = 'TOGGLE_OVERLAY';
export const HANDLE_SEARCH_SUBMIT = 'HANDLE_SEARCH_SUBMIT';