export const UPDATE_NAMES = 'UPDATE_NAMES';
export const DELETE_PERSON = 'DELETE_PERSON';
export const TOGGLE_PERSON = 'TOGGLE_PERSON';


export const COCKPIT_ON_EXITING = 'COCKPIT_ON_EXITING';
export const COCKPIT_ON_EXITED = 'COCKPIT_ON_EXITED';
export const COCKPIT_NEXT = 'COCKPIT_NEXT';
export const COCKPIT_PREV = 'COCKPIT_PREV';